file_min_updated_hours: 5
site:
  url: https://www.trackawesomelist.com
  title: "Track Awesome List"
  description:
    "We track over 500 awesome list updates, and you can also subscribe to daily or weekly updates via RSS or News Letter."
sources:
  k4m4/terminals-are-sexy:
    category: Development Environment
    default_branch: master
    files:
      readme.md:
        index: true
  sdras/awesome-actions:
    category: Development Environment
    default_branch: main
    files:
      README.md:
        index: true
  rothgar/awesome-tmux:
    category: Development Environment
    default_branch: master
    files:
      README.md:
        index: true
  awesome-foss/awesome-sysadmin:
    category: Development Environment
    default_branch: master
    files:
      README.md:
        index: true
  dreikanter/sublime-bookmarks:
    category: Editors
    default_branch: master
    files:
      README.md:
        index: true
  mhinz/vim-galore:
    category: Editors
    default_branch: master
    files:
      README.md:
        index: true